# ----------------------------------------------------------------------------
# Basic setup
# ----------------------------------------------------------------------------
dataset: kitti
seed: 4869
image:
  height: 370
  width: 1226
  ext: jpg
seq: "10"
result_dir: result/tmp/0

# ----------------------------------------------------------------------------
# tracking options
# ----------------------------------------------------------------------------
feature_tracking_method: 1
  # 1: deep optical flow

tracking_method: 3 
  # 3: hybrid

compute_2d2d_pose:
  ransac:
    reproj_thre: 0.2
    repeat: 5
  validity:
    method: flow+chei
    min_flow: 5 

PnP:
  ransac:
    iter: 1000
    reproj_thre: 1
    repeat: 5
  kp_src: kp_list # [kp_list, kp_best]

# translation scale
translation_scale:
  ransac:
    min_samples: 3
    max_trials: 100
    stop_prob: 0.99
    thre: 1
  kp_src: kp_list # [kp_list, kp_best]

# ----------------------------------------------------------------------------
# Deep single-view depth
# ----------------------------------------------------------------------------
depth:
  depth_src:  # (blank: deep model inference; 0: GT depth)
  max_depth: 50
  min_depth: 0
  pretrained_model: model_zoo/depth/kitti_odom/stereo/

# ----------------------------------------------------------------------------
# Deep Optical Flow
# ----------------------------------------------------------------------------
deep_flow:
  forward_backward: True
  num_kp: 2000
  kp_sel_method: bestN
  network: liteflow  
    # liteflow: LiteFlowNet
  flow_net_weight: model_zoo/optical_flow/LiteFlowNet/network-default.pytorch
  batch_size: 1
  precomputed_flow: 

crop:
  depth_crop: [[0.3, 1], [0, 1]]
  flow_crop: [[0, 1], [0, 1]]

# ----------------------------------------------------------------------------
# Visualization
# ----------------------------------------------------------------------------
visualization:
  window_h: 900
  window_w: 1500
  save_img: False
  flow: 
    vis_full_flow: True
    vis_back_flow: True
    vis_flow_diff: True
  match:
    kp_num: 50  # -1 for using all
    vis_type: 2
      # None: None
      # 0: draw_match_2_side
      # 1: draw_match_temporal
      # 2: both
  trajectory:
    vis_traj: True
    draw_scale: 0.8
    mono_scale: 1 #5.4; 0.2
    vis_gt_traj: True
  depth:
    use_tracking_depth: False
    vis_full_depth: False
    vis_full_disp: True

# ----------------------------------------------------------------------------
# Directories
# ----------------------------------------------------------------------------
directory:
  gt_pose_dir: dataset/kitti_odom/gt_poses/
  img_seq_dir: dataset/kitti_odom/odom_data/
  depth_dir: dataset/kitti_odom/depth/
